name: Unit Testing in .NET with XUnit and MoQ

on:
  push:
    branches:
    - "main"
  pull_request:
    branches:
    - "**"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Check out
        uses: actions/checkout@v3

      - name: Build and test done folder
        run: |
          cd done
          dotnet restore

          dotnet build
          dotnet test --logger "junit;LogFilePath=../results/test-results.xml"  --collect:"XPLat Code Coverage"   
          
      - name: ReportGenerator
        uses: danielpalme/ReportGenerator-GitHub-Action@5.3.5
        with:
          reports: "**/coverage.cobertura.xml"
          targetdir: "done/results"
          reporttypes: MarkdownSummaryGithub

      - name: Upload coverage report artifact
        uses: actions/upload-artifact@v4
        with:
          name: CoverageReport # Artifact name        
          path: done/results # Directory containing files to upload

      - name: Lists done/results folder
        run: ls -al done/results
        shell: bash
          

      - name: Publish coverage in build summary # Only applicable if 'MarkdownSummaryGithub' or one of the other Markdown report types is generated
        run: cat done/results/SummaryGithub.md >> $GITHUB_STEP_SUMMARY # Adjust path and filename if necessary
        shell: bash
          


          
          

        

