name: Unit Testing in .NET with XUnit and MoQ

on:
  push:
    branches:
    - "main"
  pull_request:
    branches:
    - "**"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Check out
        uses: actions/checkout@v3

      #- name: Restore coverage history
      #  uses: dawidd6/action-download-artifact@v3
      #  with:
      #    name: CoverageHistory
      #    path: CoverageHistory
      #    continue-on-error: true

      - name: Build and test done folder
        run: |
          cd done
          dotnet restore

          dotnet build
          dotnet test --logger "junit;LogFilePath=../results/test-results.xml"  --collect:"XPLat Code Coverage"   
          
      - name: Generate Coverage Report
        uses: danielpalme/ReportGenerator-GitHub-Action@5
        with:
          reports: "${{ github.workspace }}/**/*coverage.cobertura.xml"
          sourcedirs: "${{ github.workspace }}/"
          targetdir: coveragereport_${{ github.run_number }}
          reporttypes: 'HtmlInline;Cobertura'
          
      - name: Test Report
        uses: dorny/test-reporter@v1 
        if: always()
        with:
          name: test-results
          path: "done/results/**/*.xml"
          reporter: java-junit

      - name: Upload CoverageReportFiles
        uses: actions/upload-artifact@v4
        with:
          name: CoberturaCodeCoverageReport
          path: coveragereport_${{ github.run_number }}/

      - name: Get all zip files
        id: filelist
        uses: the-coding-turtle/ga-file-list@v0.1
        with:
          directory: coveragereport_${{ github.run_number }}/
          file_extension: "*.zip"

      - name: Extract tgz
        uses: ihiroky/extract-action@v1
        with:
          file_path: coveragereport_${{ github.run_number }}/CoberturaCodeCoverageReport.zip
          extract_dir: extracted-folder

      - name: Upload Extracted Files
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-html-cobertura-report
          path: extracted-folder


          


          
          

        

